# Generated by Django 4.1.4 on 2022-12-16 02:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "recipe_id",
                    models.BigAutoField(
                        help_text="Recipe ID", primary_key=True, serialize=False
                    ),
                ),
                ("recipe_title", models.CharField(max_length=100)),
                ("recipe_main_ingre", models.CharField(max_length=100)),
                ("recipe_total_ingre", models.CharField(max_length=100)),
                ("recipe_serving", models.CharField(max_length=100)),
                ("recipe_time", models.CharField(max_length=100)),
                ("recipe_image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigAutoField(
                        help_text="User ID", primary_key=True, serialize=False
                    ),
                ),
                ("user_pw", models.CharField(max_length=100)),
                ("user_name", models.CharField(max_length=100)),
                ("user_gender", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Refrigerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingre_id", models.CharField(max_length=100)),
                ("main_ingre", models.CharField(max_length=100)),
                (
                    "expiration",
                    models.DateField(
                        default=datetime.datetime(2022, 12, 16, 11, 39, 1, 794972)
                    ),
                ),
                (
                    "refri_user_id",
                    models.ForeignKey(
                        db_column="refri_user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="refri_user",
                        to="refrigerator.user",
                    ),
                ),
            ],
        ),
    ]
