# Generated by Django 4.1.4 on 2022-12-16 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("refrigerator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="refrigerator", name="id",),
        migrations.AlterField(
            model_name="refrigerator",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 16, 14, 34, 16, 699101)
            ),
        ),
        migrations.AlterField(
            model_name="refrigerator",
            name="ingre_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.BigAutoField(
                help_text="User ID", primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Favorite_Recipe",
            fields=[
                ("fav_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(default=0)),
                (
                    "fav_recipe_id",
                    models.ForeignKey(
                        db_column="fav_recipe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fav_recipe",
                        to="refrigerator.recipe",
                    ),
                ),
                (
                    "fav_user_id",
                    models.ForeignKey(
                        db_column="fav_user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fav_user",
                        to="refrigerator.user",
                    ),
                ),
            ],
        ),
    ]
