# Generated by Django 4.1.4 on 2022-12-16 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "refrigerator",
            "0002_remove_refrigerator_id_alter_refrigerator_expiration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="refrigerator",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 16, 14, 44, 31, 342626)
            ),
        ),
    ]
