# Generated by Django 4.1.4 on 2022-12-16 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refrigerator", "0003_alter_refrigerator_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refrigerator",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 16, 14, 48, 10, 370480)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
