# Generated by Django 4.1.4 on 2022-12-16 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refrigerator", "0004_alter_refrigerator_expiration_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_order",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="refrigerator",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 16, 15, 12, 43, 793486)
            ),
        ),
    ]
