# Generated by Django 4.1.4 on 2022-12-23 04:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("refrigerator", "0005_recipe_recipe_order_alter_refrigerator_expiration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_up", models.ImageField(null=True, upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="favorite_recipe",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_order",
            field=models.CharField(default="", max_length=1500),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_total_ingre",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="refrigerator",
            name="expiration",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="favorite_recipe",
            constraint=models.UniqueConstraint(
                fields=("fav_user_id", "fav_recipe_id"), name="unique favorite"
            ),
        ),
    ]
