# Generated by Django 4.1.4 on 2022-12-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refrigerator", "0006_image_alter_favorite_recipe_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_up",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="refrigerator",
            name="ingre_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
