# Generated by Django 4.1.4 on 2022-12-28 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("refrigerator", "0007_alter_image_image_up_alter_refrigerator_ingre_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite_recipe",
            name="fav_recipe_id",
            field=models.ForeignKey(
                db_column="fav_recipe_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fav_recipe",
                to="refrigerator.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="favorite_recipe",
            name="fav_user_id",
            field=models.ForeignKey(
                db_column="fav_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fav_user",
                to="refrigerator.user",
            ),
        ),
        migrations.AlterField(
            model_name="refrigerator",
            name="refri_user_id",
            field=models.ForeignKey(
                db_column="refri_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refri_user",
                to="refrigerator.user",
            ),
        ),
    ]
